# Generated by Django 3.2.9 on 2024-06-07 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('publisher', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('language', models.CharField(max_length=50)),
                ('likes', models.PositiveBigIntegerField(default=0)),
                ('price', models.PositiveBigIntegerField(default=0)),
                ('year_of_publishing', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books_authored', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books_in_category', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
