# Generated by Django 5.0.6 on 2024-07-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='in_wishlist',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
