# Generated by Django 3.2.9 on 2024-06-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_auto_20240608_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=700),
        ),
        migrations.AlterField(
            model_name='books',
            name='description',
            field=models.CharField(max_length=700),
        ),
        migrations.AlterField(
            model_name='books',
            name='publisher',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='books',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
