# Generated by Django 3.2.9 on 2024-06-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_rename_books_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='sold_off_credit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='sold_on_credit',
            field=models.BooleanField(default=False),
        ),
    ]
