# Generated by Django 3.2.9 on 2024-06-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0005_auto_20240609_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='sold_off_credit',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='sold_on_credit',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
