# Generated by Django 3.2.9 on 2024-06-09 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0006_auto_20240609_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='sold_off_credit',
        ),
    ]
