# Generated by Django 3.2.9 on 2024-06-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0007_remove_book_sold_off_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='sold_on_credit',
            field=models.BooleanField(db_index=True, default=None, null=True),
        ),
    ]
