# Generated by Django 3.2.9 on 2024-06-09 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0010_order_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='quantity',
            new_name='copies',
        ),
    ]
