# Generated by Django 3.2.9 on 2024-06-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0011_rename_quantity_order_copies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='sold_on_credit',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
    ]
