# Generated by Django 3.2.9 on 2024-06-17 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0012_alter_book_sold_on_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='img_url',
            field=models.CharField(default='https://bookstoreromanceday.org/wp-content/uploads/2020/08/book-cover-placeholder.png', max_length=500),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(default='9780957037885', max_length=300),
            preserve_default=False,
        ),
    ]
