# Generated by Django 3.2.9 on 2024-06-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0013_auto_20240617_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='img_url',
            field=models.CharField(default='https://bookstoreromanceday.org/wp-content/uploads/2020/08/book-cover-placeholder.png', max_length=500),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='year_of_publishing',
            field=models.CharField(max_length=200),
        ),
    ]
