# Generated by Django 3.2.9 on 2024-06-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0014_auto_20240617_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='img_url',
            field=models.CharField(max_length=500),
        ),
    ]
