# Generated by Django 3.2.9 on 2024-06-17 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0015_alter_book_img_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='img_url',
        ),
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
    ]
