# Generated by Django 3.2.9 on 2024-06-17 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0016_auto_20240617_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='bio',
        ),
    ]
