# Generated by Django 3.2.9 on 2024-06-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0017_remove_author_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='bio',
            field=models.CharField(max_length=800, null=True),
        ),
    ]
