# Generated by Django 3.2.9 on 2024-06-17 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0018_author_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='description',
        ),
        migrations.RemoveField(
            model_name='book',
            name='language',
        ),
        migrations.RemoveField(
            model_name='book',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
    ]
