# Generated by Django 3.2.9 on 2024-06-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0019_auto_20240617_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.CharField(max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='img_url',
            field=models.CharField(default='https://bookstoreromanceday.org/wp-content/uploads/2020/08/book-cover-placeholder.png', max_length=500),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(default='9784186989427', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(default='English', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='likes',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(default='Macmillan', max_length=200),
            preserve_default=False,
        ),
    ]
