# Generated by Django 3.2.9 on 2024-06-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0020_auto_20240617_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(default='9780957037885', max_length=200),
        ),
    ]
