# Generated by Django 3.2.9 on 2024-06-24 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0021_alter_book_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='sales',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
