# Generated by Django 3.2.9 on 2024-06-24 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0022_book_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='in_cart',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='in_cart',
            field=models.BooleanField(default=False),
        ),
    ]
